spring:
  application:
    name: Payment
    version: 1.0.0

  datasource:
    url: jdbc:h2:./db/payment;AUTO_SERVER=TRUE
    username: root
    password:
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  security:
    user:
      name: email
      password: password

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

  file:
    name: logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

server:
  port: 8888
